version: '3'

services:
    mysql:
        image: mysql:8.0.34
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: test
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
            - ./scripts:/docker-entrypoint-initdb.d
        depends_on:
            - php
    php:
        container_name: php
        build:
            dockerfile: ./Dockerfile
        volumes:
            - ./php/:/var/www/html
        ports:
            - "9000:80"
volumes:
    db_data: